name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5

    - name: Ruby cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle check || bundle install
    - name: Pods cache
      uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}

    - name: Pod install
      run: |
        if [ ! -d "Pods" ]; then
          bundle exec pod install
        fi
    - name: Build and test
      run: bundle exec fastlane ci_check